# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1189ebb96926a724ec5df10a509296b456da9a263617d0e00966baed60267870b7b744b6ddb168d24bab4e145e679a38cdda33a6ded2cfc03c07719f5f6932d

test:
  secret_key_base: 457635fe854e0f27dee5038a4efe33598b230183382ca6dd360bc24a87829177a1a89c7d2d491bec6419e0667087461e556f395c7bb2b0b33ccf904d5701d2ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
