default: &default
  # corpid: "corpid"
  # corpsecret: "corpsecret"
  # agentid:  1
  # Or if using public account, only need above two line
  appid: "wx60a5fde4d0806f41"
  secret: "7ac60e7d74da78967d47af72632990ec"
  # token:    "my_token"
  # access_token: "C:/Users/[username]/wechat_access_token"
  # encrypt_mode: false # if true must fill encoding_aes_key
  # encoding_aes_key:  "my_encoding_aes_key"
  # jsapi_ticket: "C:/Users/[user_name]/wechat_jsapi_ticket"

production:
# Or if using public account, only need above two line
  appid: ''
  secret: ''

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default

staging:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"
  appid: ""
  secret: ""
